server:
  port: 8030
eureka:
  client:
    serviceUrl:   #设置注册中心的地址： 与 eureka-server 中的配置 application.yml 遥相呼应
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server     #表示这个微服务本身的名称是 product-data-service
  cloud:
    config:
      label: master         #表示git的master分支
      server:
        git:
          uri: https://github.com/70416450/cloud-config
          searchPaths: conf       #目录结构


